### PR TITLE
- Adds support for instanceof in PHP to Python conversion

### PR DESCRIPTION
**Pull request by beh9540**
Adds support for instanceof -> isinstance mapping

### CODE REVIEW

**Comment by viraptor** [comment]
Thanks for the contribution! There are some random whitespace issues, but I'm happy to merge the change when they're fixed.

**Comment by beh9540** [comment]
Sorry, Pycharm trying to clean things up to it's way. I'll fix that.

**Comment by viraptor** [comment]
Thank you very much. Sorry for the long wait. I just took over the project and I'll try to get it active again. :)

**Comment by soulseekah** [comment]
You're on a roll today, @viraptor :+1: 

Glad to see the project breathing again :)

**Pull request merged**
