### PR TITLE
Ensure parsetab is generated at install time

### LINKED ISSUE #32: Please precompile parser at setup time
According to [Ply packaging advices](http://www.dabeaz.com/ply/ply.html#ply_nn49) it is recommended to precompile the parser during installation. Without it it might have to be compiled again and again if phply is installed systemwide as root, but executed as regular user. Can you please implement this?

### PR DESCRIPTION
**Pull request by nijel**
This way it is available even on global installation.

Fixes #32

### CODE REVIEW

**Comment by viraptor** [comment]
I'm not a great fan of doing this on every setup.py run. I'll have a look if there's any way to add this as a step to `sdist`.

**Comment by nijel** [comment]
AFAIK ply should regenerate the file only if needed, so it should not be that bad. Probably it should be rather build at build time to match ply version used on the target system, when invoked in sdist only, it might still have to be regenerated on the target system as it might have newer ply version...

**Comment by viraptor** [comment]
I'll give this a go when I have a moment: https://stackoverflow.com/a/46909717/31667

**Comment by nijel** [comment]
Closing this as different approach has been implemented.

**Pull request closed without merging**
